services:
  - type: web
    name: expense-tracker-api
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 -m uvicorn backend.expense_api:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
